usage() {
	# editorconfig-checker-disable
	cat <<EOF
Usage: one $t enable [OPTIONS] <NAME> [<NAME>...]
Desc:  Enable matched $t
Arguments:
  <NAME>                  $t name
Options:
  -r <repo>               Enable matched $t in the repo
EOF
	# editorconfig-checker-enable
}

# NOTE: DO NOT modify the value of mod_annotation
readonly mod_annotation='# This file is generated by one.bash. Do not modify the file content.'

# Create completion mod file
create_mod() {
	local name=$1 opt_path=$2
	local -n output=$3
	local MOD_DATA_ROOT="$ONE_DIR/data/$t"
	local MOD_DATA_DIR="$MOD_DATA_ROOT/${name}"
	local MOD_FILE="$MOD_DATA_DIR/mod.bash"
	local MOD_META="$MOD_DATA_DIR/meta.bash"
	local log_tag="enable:$t:$name"
	local repo_name

	repo_name=$(get_enabled_repo_name "$opt_path")
	log_verb "$log_tag:mod_meta" "opt_path=$opt_path repo_name=$repo_name"

	(
		# shellcheck disable=1090
		. "$opt_path"
		if declare -F AFTER_DOWNLOAD &>/dev/null; then
			log_verb "$log_tag" "To execute AFTER_DOWNLOAD fucntion"
			(
				cd "$MOD_DATA_DIR" || return 43
				AFTER_DOWNLOAD 2>&1 | tee -a "$ONE_LOG_FILE" >&2
			) || {
				log_err "$log_tag" "Failed to execute AFTER_DOWNLOAD function"
				return 7
			}
		fi
	)

	{
		echo "$mod_annotation"
		echo "repo_name=$repo_name"
	} >"$MOD_META"

	echo "$mod_annotation" >"$MOD_FILE"

	(
		# shellcheck disable=1090
		source "$opt_path"

		if [[ -n ${PRIORITY:-} ]]; then
			echo "# ONE_LOAD_PRIORITY: $PRIORITY" >>"$MOD_FILE"
		fi

		if [[ -n ${ABOUT:-} ]]; then
			echo "about-plugin '$ABOUT'" >>"$MOD_FILE"
		fi

		if [[ -n ${DEPS:-} ]]; then
			echo "one-bash:mod:deps $DEPS" >>"$MOD_FILE"
		fi

		if declare -F INSERT &>/dev/null; then
			log_verb "$log_tag" "To copy INSERT fucntion"
			{
				printf -- '\n'
				declare -f INSERT | sed -e '1,2d;$d' -e 's/^    //'
			} >>"$MOD_FILE"
		fi

		if declare -F RUN_AND_INSERT &>/dev/null; then
			log_verb "$log_tag" "To execute RUN_AND_INSERT fucntion"
			(
				cd "$MOD_DATA_DIR" || return 44
				printf -- '\n'
				RUN_AND_INSERT
			) >>"$MOD_FILE"
		fi

		if [[ -n ${GIT_REPO:-${GITHUB_REPO:-}} ]]; then
			if [[ -n ${SCRIPT:-} ]]; then
				echo "source \"\$ONE_DIR/data/$t/$name/git/${SCRIPT}\"" >>"$MOD_FILE"
			fi
		elif [[ -n ${SCRIPT:-} ]]; then
			echo "source \"\$ONE_DIR/data/$t/$name/script.bash\"" >>"$MOD_FILE"
		fi

		if declare -F APPEND &>/dev/null; then
			log_verb "$log_tag" "To copy APPEND fucntion"
			{
				printf -- '\n'
				declare -f APPEND | sed -e '1,2d;$d' -e 's/^    //'
			} >>"$MOD_FILE"
		fi

		if declare -F RUN_AND_APPEND &>/dev/null; then
			log_verb "$log_tag" "To execute RUN_AND_APPEND fucntion"
			(
				cd "$MOD_DATA_DIR" || return 45
				printf -- '\n'
				RUN_AND_APPEND
			) >>"$MOD_FILE"
		fi
	)

	# echo "$MOD_FILE"
	output=$MOD_FILE
}

_enable_mod() {
	local name=$1 opt_path=$2

	(
		# shellcheck disable=1090
		source "$opt_path"

		local path
		if l.is_array BIN; then
			for path in "${BIN[@]}"; do
				create_bin_symlink "${path##*/}" bin "$ONE_DIR/data/$t/$name/git/$path"
			done
		fi
	)
}

enable_mod() {
	local name=$1 repo=$2 repo_name
	local -a filepaths=()

	search_mod "$name" "$repo" filepaths

	case ${#filepaths[@]} in
		1)
			local filepath=${filepaths[0]}
			repo_name=${filepath#"$ONE_DIR/enabled/repo/"}
			repo_name=${repo_name%%/*}

			if [[ $filepath == *.opt.bash ]]; then
				local opt_path=$filepath
				mod_check_dep_cmds "$opt_path"
				# Disable first, prevent duplicated module enabled with different priority
				disable_mod "$name"
				download_mod_data "$name" "$opt_path"

				local mod_path
				create_mod "$name" "$opt_path" mod_path
				if [[ -n ${mod_path:-} ]]; then
					filepath=$mod_path
				else
					echo "No mod file created" >&2
					return 0
				fi

				_enable_mod "$name" "$opt_path"
			else
				mod_check_dep_cmds "$filepath"
				# Disable first, prevent duplicated module enabled with different priority
				disable_mod "$name"
			fi

			local priority
			priority=$(get_priority "$filepath" "$t")
			ln -fs "$filepath" "$ONE_DIR/enabled/$priority---$name@$repo_name@$t.bash"

			printf 'Enabled: %b%s%b with priority=%b%s%b. Please restart shell to take effect.\n' \
				"$BLUE" "$repo_name/$t/$name" "$RESET_ALL" \
				"$YELLOW" "$priority" "$RESET_ALL"

			;;

		0)
			print_err "No matched $t '$name'"
			return "$ONE_EX_DATAERR"
			;;

		*)
			print_err "Matched multi $t for '$name'. You should use '-r' option for specified repo:"
			local repo
			for filepath in "${filepaths[@]}"; do
				repo=$(get_enabled_repo_name "$filepath")
				echo "   one $t enable $name -r $repo" >&2
			done
			return "$ONE_EX_USAGE"
			;;
	esac
}

. "$ONE_DIR/one-cmds/plugin/action-completion.bash"

declare -A opts=()
declare -a args=()

main() {
	if ((${#args[*]} == 0)); then
		usage
		return "$ONE_EX_OK"
	fi

	. "$ONE_DIR/one-cmds/mod.bash"

	# shellcheck source=../../bash/load-config.bash
	. "$ONE_DIR/bash/load-config.bash"

	# shellcheck source=../../bash/log.bash
	. "$ONE_DIR/bash/log.bash"

	local name
	local repo="${opts[r]:-}"
	for name in "${args[@]}"; do
		#  NOTE: Do note write like that:
		#        enable_mod "$name" "$repo" || print_err "Failed to enable '$name'."
		#  Because it leads to "set -o errexit" failure, any error returned in enable_mod
		#  would not stop executing the remaining code
		enable_mod "$name" "$repo"
	done
}
