#!/usr/bin/env bash

set -euE -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

one a disable --all
one b disable --all
one c disable --all
one d disable --all
one s disable --all
one p disable --all

one repo add ../../data/repo/_mac
one repo add git@github.com:adoyle-h/dotfiles.git
one repo add ../../data/repo/m01
one repo add git@github.com:one-bash/one-bash-it.git
one repo add git@github.com:one-bash/one.share.git

one alias enable avoid-mistakes cd general

one completion enable adoyle aliases.completion bash-completion cheat docker docker-compose.v1 exa fnm git go gvm keybase kubebuilder nvim orbctl procs taskfile yq zig

one bin enable cht diff-cheats diff-so-fancy fkill git-forgit gitcloneproxy grip highlights imgcat imgls it2dl script.bash sphinx-apidoc sphinx-autogen sphinx-build sphinx-quickstart tmux-choose-pane trim-color

one sub enable bak bash-info brew-backup brew-install brew-mirror chrome color-24 color-256 color-list cursor date debug docker-enter docker-images docker-pull docker-run doge executable gh-open git git-init-submodules htrace knowledge manpath netdata path proc-env random reload-dns script status uml2png uml2svg upload-tmp utc wifi-password

one plugin enable acme adoyle-post adoyle-pre alert asdf atuin broot completion direnv editor env-macos fnm forgit fuck fzf fzf-tab gettext gfw gnutools-for-mac go gpg grep history itmz java john k8s keymap lesspipe ls lua macos manbash manpage my-homebrew my-tmux ncurses nix nnn nvim python ruby rust shell starship vscode xcode xdg-user zl zoxide

echo "[All Done]"
