#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

if [[ -z ${ONE_DIR:-} ]]; then
  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
  readonly SCRIPT_DIR
  export ONE_DIR=$SCRIPT_DIR/..
fi

# shellcheck source=./base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../bash/load-config.bash
. "$ONE_DIR/bash/load-config.bash"

actions=(install update status)

declare -A action_alias=(
  ['i']=install
  ['u']=update
  ['s']=status
)

# one.bash:completion
# one.bash:usage
usage() {
  cat << EOF
Usage: one $(basename "$0") [<ACTION>]

Desc: Manage one.bash deps

ACTION:
  i, install          Install all deps.
  u, update [<DEP>]   Update dep. If <DEP> is omit, update all deps.
  s, status [<DEP>]   Show status of each dep. If <DEP> is omit, show all deps' status.
EOF
}

parse_cmd dep "$@"
