#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

if [[ -z ${ONE_DIR:-} ]]; then
  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
  readonly SCRIPT_DIR
  export ONE_DIR=$SCRIPT_DIR/..
fi

# shellcheck source=./base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../bash/load-config.bash
. "$ONE_DIR/bash/load-config.bash"

actions=(install update status)

declare -A action_alias=(
  ['i']=install
  ['u']=update
  ['s']=status
)

# one.bash:completion
# one.bash:usage
parse_cmd dep "$@"
