#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
  cat <<EOF
Usage: one $(basename "$0")
Desc: List all One commands
EOF
  exit 0
fi

if [[ -z ${ONE_DIR:-} ]]; then
  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
  readonly SCRIPT_DIR
  ONE_DIR=$SCRIPT_DIR/..
fi

main() {
  {
    shopt -s nullglob
    for path in "$ONE_DIR/one-cmds/"*; do
      if [[ -x $path ]]; then
        echo "${path##"$ONE_DIR/one-cmds/"}"
      fi
    done
  } | sort | uniq
}

main "$@"
