#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

# one.bash:usage
if (($# == 0)) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat << EOF
Usage: one $(basename "$0") [<ACTION>]

Desc: Manage one.bash deps

ACTION:
  i, install          Install all deps.
  u, update [<DEP>]   If <DEP> not passed, update all deps.
  s, status [<DEP>]   Show status of deps
EOF
  exit 0
fi

if [[ -z ${ONE_DIR:-} ]]; then
  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
  readonly SCRIPT_DIR
  export ONE_DIR=$SCRIPT_DIR/..
fi

# one.bash:completion
if [[ "${1:-}" == --complete ]]; then
  if ((COMP_CWORD < 3)); then
    words=(install update status --help -h)
    printf '%s\n' "${words[@]}"
  else
    case $2 in
      i | install | u | update | s | status)
        words=(composure dotbot)
        printf '%s\n' "${words[@]}"
        ;;
    esac
  fi
  exit 0
fi

git_clone() {
  local repo=$1
  local dir=$2
  if [[ -d "$dir" ]]; then return 0; fi
  shift 2

  if [[ -z ${SUBMOD:-} ]]; then
    git clone --depth 1 --single-branch "$@" "$repo" "$dir"
  else
    git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules "$@" "$repo" "$dir"
  fi
}

git_update() {
  local dir=$1 tag
  shift

  if [[ ! -d "$dir" ]]; then
    print_err "No such folder: $dir"
    return "$ONE_EX_OK"
  fi

  print_verb "To update git repo: $dir"

  git -C "$dir" fetch --recurse-submodules="${SUBMOD:-no}" "$@"
  tag=$(git -C "$dir" tag -l 'v*' --sort '-version:refname' | head -n 1)
  git -C "$dir" checkout --recurse-submodules="${SUBMOD:-no}" "$tag"
}

git_status() {
  local dir=$1
  shift
  printf '%b%s%b\n' "$REV_GREEN" "[$(basename "$dir")]" "$RESET_ALL"
  git -C "$dir" show --oneline -s
  echo ""
}

install() {
  SUBMOD=true git_clone "https://github.com/anishathalye/dotbot.git" "$ONE_DIR/deps/dotbot"
  git_clone "https://github.com/adoyle-h/composure.git" "$ONE_DIR/deps/composure"
}

update() {
  if (($# == 0)); then
    SUBMOD=true git_update "$ONE_DIR/deps/dotbot"
    git_update "$ONE_DIR/deps/composure"
  else
    if [[ "$1" == dotbot ]] || [[ "$1" == one.share ]]; then
      SUBMOD=yes git_update "$ONE_DIR/deps/$1"
    else
      git_update "$ONE_DIR/deps/$1"
    fi
  fi
}

list_status() {
  if (($# == 0)); then
    git_status "$ONE_DIR/deps/dotbot"
    git_status "$ONE_DIR/deps/composure"
  else
    git_status "$ONE_DIR/deps/$1"
  fi
}

action=$1
shift

# shellcheck source=./base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../bash/load-config.bash
. "$ONE_DIR/bash/load-config.bash"

case "$action" in
  i | install) install ;;

  u | update) update "$@" ;;

  s | status) list_status "$@" ;;

  *)
    print_err "Invalid action '$action'"
    exit $ONE_EX_USAGE
    ;;
esac
