#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

one a disable --all
one b disable --all
one c disable --all
one d disable --all
one s disable --all
one p disable --all
