#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage:-h
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
	cat <<EOF
Usage: one version
Desc:  Print current version of one.bash
EOF
	exit 0
fi

if [[ -z ${ONE_DIR:-} ]]; then
	SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
	readonly SCRIPT_DIR
	ONE_DIR=$SCRIPT_DIR/..
fi

main() {
	git -C "$ONE_DIR" describe --tags --abbrev=8 |
		sed -E 's/-([0-9]+)-g(.*)/ (commit \2, \1 commits ahead)/'
}

main "$@"
