#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

if [[ -z ${ONE_DIR:-} ]]; then
  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
  readonly SCRIPT_DIR
  export ONE_DIR=$SCRIPT_DIR/..
fi

# shellcheck source=../base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../mod-base.bash
. "$ONE_DIR/one-cmds/mod-base.bash"

# shellcheck source=../../bash/load-config.bash
. "$ONE_DIR/bash/load-config.bash"

actions=(init list add remove update info enable disable)

declare -A action_alias=(
  ['l']=list
  ['a']=add
  ['r']=remove
  ['u']=update
  ['e']=enable
  ['d']=disable
  ['i']=info
)

# one.bash:completion
parse_completion repo actions "$@"
# one.bash:usage
parse_cmd repo "$@"
