#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

if [[ -z ${ONE_DIR:-} ]]; then
	SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
	readonly SCRIPT_DIR
	export ONE_DIR=$SCRIPT_DIR/..
fi

# shellcheck source=../base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../mod-base.bash
. "$ONE_DIR/one-cmds/mod-base.bash"

actions=(list info enable disable which run help)

declare -A action_aliases=(
	['e']=enable
	['d']=disable
	['l']=list
	['i']=info
	['w']=which
	['r']=run
	['h']=help
)

# one.bash:completion
# one.bash:usage
usage() {
	cat <<EOF
Usage: one sub [-h|--help] <ACTION>

Desc:  Manage ONE_SUB commands

ACTION:
  e, enable <NAME>...        Enable matched sub commands
  d, disable <NAME>...       Disable matched sub commands
  l, list                    List sub commands in each REPO/sub
  i, info <NAME>             Show information of matched sub commands
  w, which <NAME>            Show realpath of sub command
  r, run <NAME> [<ARGS>...]  Run sub command
  h, help                    Print the usage of ONE_SUB command
EOF
}

parse_cmd sub "$@"
