#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

if [[ -z ${ONE_DIR:-} ]]; then
	ONE_DIR=$(realpath "$0")
	ONE_DIR=${ONE_DIR%/*}
	ONE_DIR=${ONE_DIR%/*}
	ONE_DIR=${ONE_DIR%/*}
	declare -rx ONE_DIR
fi

# shellcheck source=../base-scripts.bash
. "$ONE_DIR/one-cmds/base-scripts.bash"

# shellcheck source=../mod-base.bash
. "$ONE_DIR/one-cmds/mod-base.bash"

actions=(list info enable edit disable which run help)

declare -A action_aliases=(
	['e']=enable
	['d']=disable
	['l']=list
	['i']=info
	['w']=which
	['r']=run
	['h']=help
)

readonly t=sub

# one.bash:completion
# one.bash:usage
usage() {
	# editorconfig-checker-disable
	cat <<EOF
Usage: one sub [-h|--help] <ACTION>

Desc:  Manage ONE_SUB commands

Action:
  e, enable <NAME>...        Enable matched sub commands
  d, disable <NAME>...       Disable matched sub commands
  l, list                    List sub commands in each repo
  i, info <NAME>             Show information of matched sub commands
  w, which <NAME>            Show realpath of sub command
  edit <NAME>                Edit matched sub file
  r, run <NAME> [<ARGS>...]  Run sub command
  h, help                    Print the usage of ONE_SUB command
EOF
	# editorconfig-checker-enable
}

parse_cmd sub "$@"
