#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

mac() {
	cat <<EOF >"$PAYLOAD"
{
  "inputs": {
    "OS": "[\"macos-12\"]",
    "BASHVER": "$BASHVER"
  }
}
EOF
}

linux() {
	cat <<EOF >"$PAYLOAD"
{
  "inputs": {
    "OS": "[\"ubuntu-22.04\"]",
    "BASHVER": "$BASHVER"
  }
}
EOF
}

PAYLOAD=$SCRIPT_DIR/../tmp/act-payload.json
TYPE=$1
BASHVER="[\\\"${2:-4.4}\\\"]"

case $TYPE in
	mac) mac "$@" ;;
	linux) linux "$@" ;;
esac

act -j localhost -e "$PAYLOAD"
