#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

# Create your dotfiles
DOTFILES_DIR=$ONE_DIR/dotfiles
mkdir -p "$DOTFILES_DIR"

export ONE_CONF=$DOTFILES_DIR/one.config.bash
mkdir -p "$(dirname "$ONE_CONF")"

cat <<-EOF >"$ONE_CONF"
	DOTFILES_DIR="$DOTFILES_DIR"

	ONE_DEBUG=false
	ONE_LINKS_CONF() {
	  case "\$1" in
	    *) echo "$DOTFILES_DIR"/one.links.yaml ;;
	  esac
	}
EOF
