name: CI

on:
  push:
    branches:
      - 'test/**'
      - develop
    tags:
      - v*

  pull_request:
    branches:
      - develop

  workflow_dispatch:
    inputs: {}

jobs:
  ci:

    if: "!(
      startsWith(github.event.head_commit.message, 'docs:') ||
      startsWith(github.event.head_commit.message, 'ci:') ||
      startsWith(github.event.head_commit.message, 'chore:') ||
      startsWith(github.event.head_commit.message, 'style:')
      )"

    uses: ./.github/workflows/test.yaml
    with:
      OS: '["macos-12", "ubuntu-22.04"]'
      BASHVER: '["4.4","5.0","5.1","5.2","5.2.9"]'
