name: CI

on:
  push:
    branches:
      - 'test/**'
      - develop
    tags:
      - v*

  pull_request:
    branches:
      - develop

  workflow_dispatch:
    inputs: {}

jobs:

  alpine:
    runs-on: ubuntu-22.04

    if: "!(
      startsWith(github.event.head_commit.message, 'docs:') ||
      startsWith(github.event.head_commit.message, 'ci:') ||
      startsWith(github.event.head_commit.message, 'chore:') ||
      startsWith(github.event.head_commit.message, 'style:')
      )"

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        # 5.2 and 5.2.9 are same in bash docker image
        BASHVER: ['4.0', '4.1', '4.2', '4.3', '4.4', '5.0', '5.1', '5.2']

    steps:
      - uses: actions/checkout@v3
      - run: BASHVER=${{ matrix.BASHVER }} BUILD_DIST=true PULL_IMAGE=true ./tools/test-in-docker

  host:
    if: "!(
      startsWith(github.event.head_commit.message, 'docs:') ||
      startsWith(github.event.head_commit.message, 'ci:') ||
      startsWith(github.event.head_commit.message, 'chore:') ||
      startsWith(github.event.head_commit.message, 'style:')
      )"

    uses: ./.github/workflows/test.yaml
    with:
      OS: '["macos-12", "ubuntu-22.04"]'
      BASHVER: '["4.4","5.0","5.1","5.2","5.2.9"]'
