name: local

on:
  workflow_dispatch:
    inputs:
      BASHVER:
        description: 'An array of bash verions'
        # default: '["4.4","5.0","5.1","5.2","5.2.9"]'
        default: '["4.4"]'
        required: true
        type: string

      OS:
        description: 'An array of OS'
        default: '["macos-12", "ubuntu-22.04"]'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        # 5.2 and 5.2.9 are same in bash docker image
        BASHVER: ${{ fromJSON(inputs.BASHVER) }}

    steps:
      - uses: actions/checkout@v3
      - run: PULL_IMAGE=true BASHVER=${{ matrix.BASHVER }} ./tools/test-in-docker

  localhost:
    uses: ./.github/workflows/test.yaml
    with:
      OS: ${{ fromJSON(inputs.OS) }
      BASHVER: ${{ fromJSON(inputs.BASHVER) }}
