name: local

on:
  workflow_dispatch:
    inputs: {}

jobs:
  linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        # 5.2 and 5.2.9 are same in bash docker image
        BASHVER: ['4.4']
        # BASHVER: ['4.4', '5.0']

    steps:
      - uses: actions/checkout@v3
      - run: PULL_IMAGE=true BASHVER=${{ matrix.BASHVER }} ./tools/test-in-docker

  mac:
    runs-on: macos-12

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        BASHVER: ['4.4', '5.0']

    steps:
      - uses: actions/checkout@v3

      - name: Init
        run: |
          echo "PWD: $PWD"
          echo "ACT: ${{ env.ACT }}"

      - name: Cache bash
        if: ${{ !env.ACT }}
        id: cache-bash
        uses: actions/cache@v3
        with:
          path: ./tmp/bash-${{ matrix.BASHVER }}
          key: ${{ runner.os }}-bash-${{ matrix.BASHVER }}

      - name: Cache deps
        if: ${{ !env.ACT }}
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ./deps/compose
            ./deps/dotbot
            ./deps/one.share
            ./deps/bash-it
          key: ${{ runner.os }}-one-deps

      - name: Install bash
        if: steps.cache-bash.outputs.cache-hit != 'true'
        run: |
          BASHVER=${{ matrix.BASHVER }} ./tools/install-bash

      - name: Prepare
        run: |
          export PATH="${{ github.workspace }}/tmp/bash-${{ matrix.BASHVER }}/bin:$PATH"
          bash --version

          export ONE_DIR=${{ github.workspace }}
          ./tools/ci-init

      - name: Install one.bash deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          export ONE_DIR=${{ github.workspace }}
          export PATH="$ONE_DIR/bin:$PATH"
          # Install Dependencies
          one deps install

      - name: Start to test
        run: |
          export PATH="${{ github.workspace }}/tmp/bash-${{ matrix.BASHVER }}/bin:$PATH"
          export ONE_DIR=${{ github.workspace }}
          ./tools/test
